version: '3'

vars:
  PACKAGE_NAME: travelpaths
  R_CMD: R

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list

  clean_pkg:
    desc: Remove previous built packages
    cmds:
      - rm -f {{.PACKAGE_NAME}}_*.tar.gz

  clean:
    desc: Clean build artifacts
    deps: [clean_pkg]
    cmds:
      - rm -rf {{.PACKAGE_NAME}}.Rcheck
      - rm -rf man/
      - rm -rf docs/

  docs:
    desc: Generate documentation using roxygen2
    cmds:
      - "{{.R_CMD}} -e 'roxygen2::roxygenize(\".\", c(\"rd\", \"namespace\"))'"

  build-fast:
    desc: Build the package
    deps: [docs]
    cmds:
      - "{{.R_CMD}} CMD build --no-build-vignettes ."

  build:
    desc: Build the package
    deps: [docs, clean_pkg]
    cmds:
      - "{{.R_CMD}} CMD build ."

  fbuild:
    desc: Build the package fast
    deps: [docs, clean_pkg]
    cmds:
      - "{{.R_CMD}} CMD build --no-build-vignettes ."

  inst:
    desc: Install the package locally
    deps: [build]
    cmds:
      - "{{.R_CMD}} CMD INSTALL {{.PACKAGE_NAME}}_*.tar.gz"

  finst:
    desc: Install the package locally
    deps: [fbuild]
    cmds:
      - "{{.R_CMD}} CMD INSTALL {{.PACKAGE_NAME}}_*.tar.gz"

  install-deps:
    desc: Install package dependencies
    cmds:
      - "{{.R_CMD}} -e 'devtools::install_deps(dependencies = TRUE)'"

  check:
    desc: Run R CMD check on the package
    deps: [build]
    cmds:
      - "{{.R_CMD}} CMD check {{.PACKAGE_NAME}}_*.tar.gz"

  check_as_cran:
    desc: Run R CMD check on the package
    deps: [build]
    cmds:
      - "{{.R_CMD}} CMD check --as-cran {{.PACKAGE_NAME}}_*.tar.gz"

  vignette:
    desc: Build vignettes
    cmds:
      - "{{.R_CMD}} -e 'devtools::build_vignettes()'"

  vignette_extending:
    desc: Extract vignettes
    env:
      NO_SMOOVE_VIGNETTE: "TRUE"
      NO_TRAVELPATHS_VIGNETTE: "TRUE"
    cmds:
      - "{{.R_CMD}} -e 'devtools::build_vignettes()'"

  test:
    desc: Run Test
    cmds:
      - "{{.R_CMD}} -f 'tests/tinytest.R'"

  test_smoke:
    desc: Run Test
    env:
      TINYTEST_SMOKE: "TRUE"
    cmds:
      - "{{.R_CMD}} -f 'tests/tinytest.R'"

  test_local:
    cmds:
      - "{{.R_CMD}} --quiet -e 'travelpaths:::dev_run_tests()'"
